getsentry/action-visual-snapshot

- .github/workflows/release.yml
Due to a security vulnerability, `add-path` is deprecated, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> fix: Fix `add-path` deprecation

- __tests__/util/saveSnapshots.test.ts
- src/main.ts
- src/util/saveSnapshots.ts
This fixes the case where `saveSnapshot` fails when we only want to save
snapshots. Previously, we missed the error case where the rest of the
script would continue to run when we should instead be returning early.
This also changes `saveSnapshots` to retry 5 times before throwing.
> feat: Fix `saveSnapshots` failing

- package.json
- yarn.lock
To handle:
https://github.com/advisories/GHSA-wgfq-7857-4jcc
These are the changes included:
https://github.com/googleapis/nodejs-storage/blob/master/CHANGELOG.md#540-2020-10-29
> chore(security): Upgrade @google-cloud/storage to upgrade json-bigint

- src/util/diffSnapshots.ts
We are being limited by the UI to show spans after diffing snapshots because we are exceeding the limit span limit. The spans on files themselves do not seem to be particularly interesting (I would expect diffing to have linear performance with file size as the diffs basically compare px by px from both images).
> ref(diffSnapshots): remove fileSpan

- __mocks__/@actions/github.ts
- __tests__/api/getArtifactsForBranchAndWorkflow.test.ts
- __tests__/api/retrieveBaseSnapshots.test.ts
- package.json
- src/api/downloadOtherWorkflowArtifact.ts
- src/api/failBuild.ts
- src/api/finishBuild.ts
- src/api/getArtifactsForBranchAndWorkflow.ts
- src/api/startBuild.ts
- src/main.ts
- yarn.lock
`actions/github` has better typing. Biggest change is to call the api methods from `octokit.rest` instead of `octokit`.
* https://github.com/actions/toolkit/blob/main/packages/github/RELEASES.md
* https://github.com/actions/toolkit/blob/main/packages/artifact/RELEASES.md
* https://github.com/actions/toolkit/blob/main/packages/exec/RELEASES.md
* https://github.com/actions/toolkit/blob/main/packages/glob/RELEASES.md
* https://github.com/actions/toolkit/blob/main/packages/io/RELEASES.md
> feat: Upgrade `actions/github` and other gh actions

- package.json
- src/util/uploadToGcs.ts
- yarn.lock
Since all the files are generated, we can trigger an upload and saturate the network instead of awaiting each file to upload.
I tried checking our sentry dashboard on how long this step takes, but we cannot see the upload span in our dashboard because we are exceeding the span limit.
Tests results (uploading 848 snapshots)
- **sequential** timed out https://github.com/getsentry/sentry/pull/34355/checks?check_run_id=6394113486 
this run took more than 50minutes, the 2nd time I triggered it should show [here](https://sentry.io/organizations/sentry/performance/summary/?project=5324467&query=transaction.duration%3A%3C15m+transaction.op%3Arun+head_ref%3Ajb%2Ftest%2Fvisual-snapshots-no-concurrency&statsPeriod=24h&transaction=visual+snapshot&unselectedSeries=p100%28%29) if it ever finishes
- …
> ref(upload): parallelize upload

- .github/workflows/release.yml
- __mocks__/@actions/github.ts
- __tests__/api/getArtifactsForBranchAndWorkflow.test.ts
- __tests__/api/retrieveBaseSnapshots.test.ts
- src/api/getArtifactsForBranchAndWorkflow.ts
The previous behavior could include "skipped" workflows that would have a status as `completed`.
Also include some other minor fixes to release workflow and test mocks
> feat: only query for successful workflows

- src/main.ts
- src/util/osTags.ts
The CI machines vary and we are very likely CPU bound when diffing snapshots. This adds two os level tags that can give us some extra info when looking at the performance data.
> feat(sentry): add os tags

- src/main.ts
Fails on master, I guess we dont always require it?
> fix(head): remove check

- action.yml
- src/main.ts
You can see a sample `development` error [here](https://sentry.io/organizations/sentry/issues/3123211249/?environment=development&project=5324467&query=is%3Aignored&statsPeriod=1h).
> feat: Set Sentry environment to production when running from main

- src/main.ts
There's various features in here:
- Setting different titles depending on the action: `save snapshots` vs `run`
- Before this, they were all named "visual snapshots" even though the top span of each was named correctly
- Report the status of a transaction (instead of currently being always unknown)
- This can be `Ok` when there are no errors and `InternalError` when anything fails
- Tag a transaction as needing approval or not
- This is useful to determine how many executions required a human to approve the execution
This means that we will be able to do the following in Discover:
- failure_rate() -> A failure is when the execution fails in an unexpected manner
- requiring approval -> The amount of times a developer is unable to merge a PR until approving a check
[A …
> feat: Rename transaction, report status and required approval tag

- src/main.ts
I'll split the runs to run on odiff/pixelmatch for a while so we can gracefully introduce the new diffing library while still collecting the data about it. This will help us quantify improvements or regressions as we switch over
> sentry(tags): tag library

- .github/workflows/release.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Committed via https://github.com/asottile/all-repos
> ref(ci): fix set-output / set-state deprecation

- package.json
- yarn.lock
This addresses github set-output and save state warnings
> Update actions/core to 1.10.0

- __mocks__/@actions/github.ts
- __tests__/api/getArtifactsForBranchAndWorkflow.test.ts
- __tests__/api/retrieveBaseSnapshots.test.ts
- package.json
- src/api/getArtifactsForBranchAndWorkflow.ts
- yarn.lock
Previously this was done by code as the API did not support passing `head_sha` to filter.
> feat: `getArtifactsForBranchAndWorkflow` to filter by `head_sha` via API

- src/api/getArtifactsForBranchAndWorkflow.ts
GitHub API treats `head_sha` with explicit `undefined` value differently than when `head_sha` does not exist in object. Want the latter.
Follow-up to #95
> fix: `head_sha` can not be in request body

- .github/workflows/test-build.yml
- .gitignore
- src/main.ts
+ add a test build workflow to make testing changes easier.
NOTE: Tested on this run with both `Visual Snapshots: Frontend` and `Visual Snapshots`: https://github.com/getsentry/sentry/runs/11178916682
> Use artifact name to differentiate results on GCS

- src/main.ts
- src/template/index.ejs
I was trying to debug the visual snapshot showing different results in the action summary vs the generated index.html and noticed this error in the logs where no changes (i.e. `all = []`) will throw an error on `cleanSelector(all[active])}` because `all[0]` results in a call `cleanSelector(undefined)`.
The logging I've added to try and make it easier to debug issues in the future.
> Don't do anything if there are no images to activate

- .github/workflows/test.yml
- src/api/startBuild.ts
This reverts the type change to startBuild to get things building (I'm honestly not sure why this works at all, but given that we are relying on this  action less, I'm going to leave it as is for now)
> Run yarn dist as part of test workflow

- __tests__/api/getArtifactsForBranchAndWorkflow.test.ts
- src/api/getArtifactsForBranchAndWorkflow.ts
- src/api/retrieveBaseSnapshots.ts
- src/main.ts
The base artifact was actually being download from an old workflow run instead of the current workflow being run.
Switching to downloadSnapshots fixes this as it uses '@actions/artifact' node module to download the artifact, but it results in a slightly different directory structure that needed to be handled.
Tested in this run: https://github.com/getsentry/getsentry/actions/runs/4492158817/jobs/7901819754
```
Results: {
"terminationReason": null,
"baseFilesLength": 9,
"changed": [
"jest/subscription-overview-displays-limited-context-for-members.png"
],
"missing": [],
"added": []
}
```
> fix: Download base artifact from current workflow
